### Numpy

In [62]:
import numpy as np

my_array = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
# print(2 * my_array)
# print("====")
# print(my_array[3,1])
# print(my_array[1:, 1:])
# print(my_array[1:, 1])
# print("====")
# print(my_array.shape)
# print(my_array[1:, 1:].shape)
# print(my_array[1:, 1].shape)
# print("====")
# print(np.zeros((2,2)))
# print(np.ones((2,2)))
# print(np.full((2,2), 5))
# print(np.random.random((2,2)))
# print(np.eye(2))
print("====")
print(my_array.reshape(2,2,3))
print(my_array.dtype)
np_float_array = np.array([1,2,3], dtype=np.float64)
print(np_float_array.dtype)
np_float_array = np.array([1.1+2.3j, 2.2, 3.6])
print(np_float_array.dtype)


====
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64
float64
complex128
